name: build-apk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true
      - name: Create key.properties
        run: |
          echo "storeFile=debug.keystore" > simple_live_app/android/key.properties
          echo "storePassword=android" >> simple_live_app/android/key.properties
          echo "keyPassword=android" >> simple_live_app/android/key.properties
          echo "keyAlias=androiddebugkey" >> simple_live_app/android/key.properties
      - name: Build APK
        run: |
          cd simple_live_app
          flutter pub get
          flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-apk
          path: simple_live_app/build/app/outputs/flutter-apk/*.apk
dependency_overrides:
  dynamic_color: 1.8.0
